CREATE TABLE IF NOT EXISTS endereco (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cep VARCHAR(10) NOT NULL,
    logradouro VARCHAR(100) UNIQUE NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    localidade VARCHAR(100) NOT NULL,
    uf VARCHAR(5) NOT NULL,
    data_hora_requisicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
